Repository project-mulplay/project-mulplay2, pull requests merged in 2023-11, with the labels that each got.

#57 Ref/#51 my page recoil, axios intercepter 생성, 프로젝트 보류기능, 프로필이미지 저장기능
  package-lock.json
  package.json
  server/controller/UserController.js
  server/repository/UserRepository.js
  server/service/UserService.js
  src/assets/image/profile0.png
  src/assets/image/profile4.png
  src/components/button/Button_funding.js
  src/components/elements/GaugeBar.js
  src/components/elements/MyBadge.css
  src/components/elements/MyDropdown.js
  src/components/layout/MainCard.js
  src/components/layout/mypage/MyCard.js
  src/components/layout/mypage/MyCategory.js
  src/components/layout/mypage/MyProfile.js
  src/components/layout/mypage/MyTable.js
  src/components/layout/mypage/ProjectManager.js
  src/hooks/useFormatDate.js
  src/pages/login/Login.js
  src/pages/mypages/MyFundingProject.js
  src/pages/mypages/MyInfoEdit.js
  src/pages/mypages/MyLikeProject.js
  src/pages/mypages/MyPages.js
  src/pages/mypages/MyProceeds.js
  src/pages/mypages/MyProjectManage.js
  src/pages/mypages/MyPwEdit.js
  src/recoil/MyCategoryAtom.js
  src/recoil/MyProjectAtom.js
  src/recoil/ProfileImgAtom.js
  src/util/api.js
Labels: feat

#61 [refactor]메인 반응형 만들기
  package-lock.json
  package.json
  src/assets/image/middle_banner.png
  src/assets/image/mobileBanner1.png
  src/assets/image/mobileBanner2.png
  src/assets/image/mobileBanner3.png
  src/components/footer/Footer.css
  src/components/head/Header.css
  src/components/layout/MiddleBanner.js
  src/components/layout/Slider.js
  src/components/layout/SubSlider.js
  src/pages/fundinglist/OpenFundingList.js
  src/pages/main/Main.css
  src/pages/main/Main.js
Labels: Refactor

#63 Feat/#59 list category 기능, 추천 최신 정렬기능 구현
  package-lock.json
  package.json
  src/components/elements/MyDropdown.js
  src/components/head/Header.js
  src/components/layout/FundingList.css
  src/components/layout/FundingList.js
  src/recoil/MyProjectAtom.js
Labels: feat

#65 헤더에 로고 바꾸기
  src/assets/image/logo.png
  src/components/head/Header.css
Labels: design

#66 Feat/#60 funding connected
  package.json
  src/App.js
  src/components/cartitem/CartItem.js
  src/components/layout/FundingList.js
  src/components/productcard/ProductCard.js
  src/data/projectData.json
  src/data/rewardData.json
  src/pages/cart/Cart.css
  src/pages/cart/Cart.js
  src/pages/funding/Funding.css
  src/pages/funding/Funding.js
  src/pages/funding/RewardCard.js
  src/pages/guidepages/guidepage.css
  src/pages/guidepages/guidepage.js
  src/pages/login/Login.css
  src/pages/login/Login.js
  src/pages/main/Main.css
  src/pages/main/Main.js
  src/pages/myproject/BasicInfo.js
  src/pages/myproject/Project.js
  src/pages/myproject/ProjectInfo.js
  src/pages/myproject/RewardInfo.js
  src/pages/myproject/TagInfo.js
  src/pages/signup/Signup.css
  src/pages/signup/Signup.js
  src/pages/store/MainReward.js
  src/pages/store/Reward.js
  src/recoil/CartAtom.js
Labels: feat, Refactor, design

#70 [fix] 곂치는 부분 제거
  src/pages/signup/Signup.js
Labels: fix

#72 프로젝트만들기, 펀딩 상세페이지, 회원가입 디자인 CSS 수정
  package.json
  server/config/db.js
  src/assets/image/banner4.png
  src/components/elements/Button_funding.js
  src/pages/funding/Funding.css
  src/pages/funding/Funding.js
  src/pages/myproject/BasicInfo.css
  src/pages/myproject/BasicInfo.js
  src/pages/myproject/DatePicker.js
  src/pages/myproject/Project.js
  src/pages/myproject/RewardInfo.css
  src/pages/signup/Signup.css
  src/pages/signup/Signup.js
Labels: design

#75 Refact/#74 chanho code fix
  server/repository/SignupRepository.js
  src/data/projectData.json
  src/data/userData.json
  src/pages/funding/Funding.css
  src/pages/funding/Funding.js
  src/pages/guidepages/guidepage.js
  src/pages/login/Login.css
  src/pages/login/Login.js
  src/pages/myproject/TagInfo.js
Labels: fix, design

#80 Ref/#73 mypage project fix
  server/controller/UserController.js
  server/repository/UserRepository.js
  server/service/UserService.js
  src/components/layout/mypage/MyCard.css
  src/components/layout/mypage/MyCard.js
  src/components/layout/mypage/ProjectManager.js
Labels: fix

#85 Ref/#73 추가된 alert css 수정
  src/pages/cart/Cart.js
  src/pages/myproject/Project.js
  src/pages/signup/Signup.js
Labels: design

#87 [init] DB 설정변경
  package-lock.json
  package.json
  server/config/db.js
  server/config/logger.js
  server/controller/UserController.js
  server/node_modules/.package-lock.json
  server/package-lock.json
  server/package.json
  server/repository/UserRepository.js
  src/components/layout/FundingList.js
  src/pages/login/Login.js
Labels: init

#91 [ref] 탈퇴기능, 리스트버그수정
  server/config/db.js
  server/repository/LoginRepository.js
  src/components/layout/FundingList.js
  src/pages/login/Login.js
  src/pages/mypages/MyInfoEdit.js
Labels: fix
