Repository project-mulplay/project-mulplay2, pull requests merged in 2023-10, with the labels that each got.

#14 [feat]메인 슬라이드 기능 추가
  package-lock.json
  package.json
  src/assets/image/banner4.png
  src/assets/image/next.png
  src/assets/image/prev.png
  src/components/layout/Slider.js
  src/pages/main/Main.css
  src/pages/main/Main.js
Labels: feat

#15 Feat/#7 mypage 비밀번호 변경 페이지 구현
  src/App.js
  src/components/elements/InputMedium.js
  src/components/layout/mypage/MyCategory.js
  src/pages/mypages/MyInfoEdit.css
  src/pages/mypages/MyInfoEdit.js
  src/pages/mypages/MyPwEdit.js
Labels: feat

#24 Feat/#18 admin
  package-lock.json
  package.json
  src/App.js
  src/components/layout/Slider.js
  src/pages/admin/Prodadmin.css
  src/pages/admin/Prodadmin.js
  src/pages/admin/Td.js
  src/pages/admin/Tr.js
  src/pages/main/Main.css
  src/pages/myproject/BasicInfo.js
  src/pages/myproject/NextBtn.js
  src/pages/myproject/Project.js
  src/pages/myproject/ProjectInfo.css
  src/pages/myproject/ProjectInfo.js
  src/pages/myproject/RewardInfo.js
  src/pages/myproject/SkillCheckbox.js
  src/pages/signup/Signup.css
Labels: feat

#28 Feat/#27 server connect && Refector/ fundingPage DB connect, css fix
  server/App.js
  server/controller/CartController.js
  server/controller/FundController.js
  server/controller/ListController.js
  server/controller/LoginController.js
  server/controller/SignupController.js
  server/repository/CartRepository.js
  server/repository/FundRepository.js
  server/repository/ListRepository.js
  server/repository/LoginRepository.js
  server/repository/SignupRepository.js
  server/service/CartService.js
  server/service/FundService.js
  server/service/ListService.js
  server/service/LoginService.js
  server/service/SignupService.js
  src/pages/cart/Cart.css
  src/pages/funding/Funding.css
  src/pages/funding/Funding.js
  src/pages/funding/RewardCard.js
  src/pages/signup/Signup.js
Labels: feat, Refactor

#29 [refactor]프로젝트 입력 체크박스로 변경
  src/pages/myproject/BasicInfo.js
  src/pages/myproject/DatePicker.js
  src/pages/myproject/Project.css
  src/pages/myproject/ProjectInfo.js
  src/pages/myproject/RewardInfo.css
  src/pages/myproject/RewardInfo.js
  src/pages/myproject/SkillCheckbox.js
  src/pages/myproject/StaffCheckbox.js
  src/pages/myproject/TagCheckbox.js
Labels: Refactor

#34 [feat] 프로젝트 제작 페이지 서버 연결
  server/.gitignore
  server/App.js
  server/controller/ProjectController.js
  server/repository/ProjectRepository.js
  server/service/ProjectService.js
  src/pages/myproject/BasicInfo.js
Labels: feat

#39 [refactor] 관리자 게시판
  package-lock.json
  package.json
  src/App.js
  src/pages/admin/AdminPage.js
  src/pages/admin/AdminPage.module.css
  src/pages/admin/Modal.css
  src/pages/admin/Modal.js
  src/pages/admin/ProdTd.js
  src/pages/admin/ProdTr.js
  src/pages/admin/Prodadmin.js
  src/pages/admin/Tr.js
  src/pages/admin/UserTd.js
  src/pages/admin/UserTr.js
  src/pages/admin/Useradmin.js
Labels: Refactor

#40 Feat/#38open punding페이지 생성, 펀딩리스트 컴포넌트생성, slider prop 추가
  src/App.js
  src/assets/image/opening1.png
  src/assets/image/opening2.png
  src/components/head/Header.js
  src/components/layout/FundingList.css
  src/components/layout/FundingList.js
  src/components/layout/ListCard.js
  src/components/layout/Slider.js
  src/pages/fundinglist/FundingListPage.js
  src/pages/fundinglist/OpenFundingList.js
  src/pages/main/Main.js
Labels: feat, design

#44 Feat/#43 프로젝트 DB 연결 및 수정
  server/controller/CartController.js
  server/controller/FundController.js
  server/controller/ListController.js
  server/controller/LoginController.js
  server/controller/ProjectController.js
  server/controller/SignupController.js
  server/repository/CartRepository.js
  server/repository/FundRepository.js
  server/repository/ListRepository.js
  server/repository/LoginRepository.js
  server/repository/ProjectRepository.js
  server/repository/SignupRepository.js
  server/service/CartService.js
  server/service/FundService.js
  server/service/ListService.js
  server/service/LoginService.js
  server/service/ProjectService.js
  server/service/SignupService.js
  src/pages/myproject/BasicInfo.js
  src/pages/myproject/DatePicker.js
  src/pages/myproject/Project.js
  src/pages/myproject/ProjectInfo.js
  src/pages/myproject/RewardInfo.css
  src/pages/myproject/RewardInfo.js
  src/pages/myproject/SkillCheckbox.js
  src/pages/myproject/StaffCheckbox.js
  src/pages/myproject/TagCheckbox.js
  src/pages/myproject/TagInfo.js
Labels: feat, Refactor, design

#45 Feat/#41 cookie, 토큰으로 로그인기능 구현
  package-lock.json
  package.json
  server/repository/LoginRepository.js
  server/repository/SignupRepository.js
  server/service/LoginService.js
  src/App.js
  src/components/elements/Tab.js
  src/components/layout/Slider.js
  src/components/layout/mypage/MyProfile.js
  src/hooks/ProjectManager.js
  src/index.js
  src/pages/login/Login.js
  src/pages/main/Main.js
  src/pages/mypages/MyInfoEdit.js
  src/pages/mypages/MyProceeds.js
  src/pages/mypages/MyPwEdit.js
  src/pages/signup/Signup.js
Labels: feat

#47 [feat] 헤더 로그인/로그아웃 상태
  src/App.js
  src/components/head/Header.js
Labels: feat

#49 Refactor/#42 header
  src/assets/image/card3.png
  src/assets/image/close.png
  src/assets/image/opening1.png
  src/assets/image/opening2.png
  src/assets/image/user_menu.png
  src/components/footer/Footer.css
  src/components/head/Header.css
  src/components/head/Header.js
  src/pages/fundinglist/OpenFundingList.css
  src/pages/fundinglist/OpenFundingList.js
  src/pages/main/Main.js
Labels: Refactor

#50 Feat/#48 main, 리스트페이지 Data 연동 css 수정
  src/components/elements/GaugeBar.js
  src/components/head/Header.js
  src/components/layout/FundingList.css
  src/components/layout/FundingList.js
  src/components/layout/MainCard.js
  src/components/layout/MainOpen.js
  src/components/layout/MainPick.js
  src/data/projectData.json
  src/pages/main/Main.css
  src/pages/main/Main.js
Labels: feat

#52 헤더 반응형 수정
  src/components/head/Header.css
  src/components/head/Header.js
  src/pages/fundinglist/OpenFundingList.css
Labels: Refactor
